server:
  port: 8889
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: yjy123456
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
  redis:
        password: 123456
        cluster:
          nodes: 192.168.175.136:7000,192.168.175.136:7001,192.168.175.136:7002,192.168.175.136:7003,192.168.175.136:7004,192.168.175.136:7005
          max-redirects: 5

logging:
  level:
    root: INFO
    org.springframework.security: INFO


