server:
  port: 8088
  servlet:
   context-path: /

spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.0.77:1521:orclkfcs
    username: zk2018
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  application:
    name: elasticsearch-demo
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.175.136:9300
